Bot1:

  backtest:
    start: 2021-05-01
    end: 2021-05-30
    interval: MINUTE_1

  service: BitTrex
  update_interval: 60 # seconds
  market: BTC-EUR
  quantity: 0.00120482 # ~ 50€ in BTC

  strat: 
    name: MacdRsiAlgorithm

    ta_params: 
      macd:
        window_slow: 26
        window_fast: 12
        window_sign: 9
      rsi:
        window: 14

    trigger_params:
      rsi_buy: 5
      rsi_sell: 80
      macd_trigger_diff: 20

Bot2:

  backtest:
    start: 2021-12-01
    end: 2021-12-18
    interval: MINUTE_1

  service: BitTrex
  update_interval: 60 # seconds
  market: BTC-EUR
  quantity: 0.00120482 # ~ 50€ in BTC

  strat: 
    name: TrendFollowing

    ta_params: 
      roc:
        window: 14

    trigger_params:
      sell_high: 3
      sell_low: -1
      buy_percentage: 1



